spring:
  application:
    name: chen-ai-agent
  ai:
    mcp:
      client:
        enabled: true
        servers-configuration: classpath:mcp-servers.json
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${AI_DASHSCOPE_API_KEY}
      chat:
        options:
          model: qwen-max
      embedding:
        options:
          model: text-embedding-v3
    # Chroma 向量数据库配置
    vectorstore:
      chroma:
        collection-name: love-app-knowledge
        initialize-schema: true
        client:
          host: http://127.0.0.1
          port: 8000

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi 接口文档的配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: io.github.chenyouxin8.chenaiagent.controller

# knife4j 的增强配置
knife4j:
  enable: true
  setting:
    language: zh_cn
# searchApi
search-api:
  api-key: ${SEARCH_API_KEY}
