package io.github.chenyouxin8.chenaiagent.task;

public enum TaskEventType {
    TASK_CREATED,
    TASK_QUEUED,
    PLAN_CREATED,
    STEP_PLANNED,
    STEP_STARTED,
    STEP_RETRY,
    STEP_COMPLETED,
    STEP_FAILED,
    AGENT_HANDOFF,
    TOOL_STARTED,
    TOOL_COMPLETED,
    TOOL_FAILED,
    METRICS_UPDATED,
    MESSAGE,
    ARTIFACT_CREATED,
    REVIEW_STARTED,
    REVIEW_COMPLETED,
    TASK_PAUSED,
    TASK_RESUMED,
    TASK_CANCELLED,
    TASK_COMPLETED,
    TASK_FAILED,
    TASK_DEAD_LETTERED
}
